CREATE TABLE PRODUCTS (
    ID SERIAL NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(20) NOT NULL,
    BRAND VARCHAR(20) NOT NULL,
    LIST_PRICE DECIMAL(10,2) NOT NULL
);
INSERT INTO PRODUCTS (ID, DESCRIPTION, BRAND, LIST_PRICE)
VALUES (DEFAULT, 'Tênis', 'ADIDAS', 299.99);
INSERT INTO PRODUCTS (ID, DESCRIPTION, BRAND, LIST_PRICE)
VALUES (DEFAULT, 'Tênis', 'VANS', 299.99);
INSERT INTO PRODUCTS (ID, DESCRIPTION, BRAND, LIST_PRICE)
VALUES (DEFAULT, 'Tênis', 'NIKE', 299.99);
INSERT INTO PRODUCTS (ID, DESCRIPTION, BRAND, LIST_PRICE)
VALUES (DEFAULT, 'Tênis', 'PUMA', 299.99);
